# Generated by Django 4.2.19 on 2025-07-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referrer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
