# Generated by Django 4.2.19 on 2025-07-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referrer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
